apiVersion: v1
kind: Template
metadata:
  labels:
    app: my-api-docker
  name: my-api-docker
parameters:
- name: DOCKER_IMAGE_TAG
  required: true

objects:

- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: my-api-docker
    name: my-api-docker
  spec:
    nodeSelector: {}
    output:
      to:
        kind: DockerImage
        name: artifactory.mydomain.com/docker-local/my-api:${DOCKER_IMAGE_TAG}
      pushSecret:
        name: secret-artifactory-docker
    postCommit: {}
    runPolicy: Parallel
    source:
      dockerfile: |-
        FROM registry.access.redhat.com/jboss-fuse-6/fis-java-openshift:2.0
        COPY *.jar /deployments
      type: Docker
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: 'fis-java-openshift:2.0'
      type: Docker
    triggers: []
  status: {}